sudo: false
language: node_js
node_js:
  - "0.12.2"
cache:
  directories:
    - bower_components
    - node_modules
install:
  - make install
script:
  - make test
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
